<KivyToggleButton>:
    orientation: 'vertical'
    size: root.size

    ToggleButton:
        id: tgb_a
        text: "トグルボタンＡ"
        on_press: root.on_togglebutton_pressed(self)

    ToggleButton:
        id: tgb_b
        text: "トグルボタンＢ"
        on_press: root.on_togglebutton_pressed(self)

    ToggleButton:
        id: tgb_c
        text: "トグルボタンＣ"
        on_press: root.on_togglebutton_pressed(self)
