<KivyCheckBox>:
    orientation: 'vertical'
    size: root.size

    CheckBox:
        id: chb_a
        group: "chb"
        active: 0
        on_state: root.on_checkbox_changed(self, self.active)

    CheckBox:
        id: chb_b
        group: "chb"
        active: 0
        on_state: root.on_checkbox_changed(self, self.active)

    CheckBox:
        id: chb_c
        group: "chb"
        active: 0
        on_state: root.on_checkbox_changed(self, self.active)
