<KivyRelativeLayout>:
    Button:
        id: btn_a
        text: "ボタンＡ"
        size_hint: (.4, .2)
        pos_hint: {'x': 0.05, 'y': 0.05}
        on_press: root.on_button_pressed(self)

    RelativeLayout:
        size: 100, 100
        pos: 100, 100

        Button:
            id: btn_b
            text: "ボタンＢ"
            size_hint:(.4, .2)
            pos_hint:{'x': 0.05, 'y': 0.05}
            on_press: root.on_button_pressed(self)
